auto:	          true

markdown:         rdiscount
pygments:         true
paginate:         6
permalink:        /:title

title:            nigelzeng.com
url:              http://nigelzeng.com
author:
    name:         nigelzeng 
description:      "nigelzeng\'s Blog"
author_info:      <a href="http://nigelzeng.com/about">nigelzeng</a>

copyright:
    - Copyright &copy; 2013 <a href="http://nigelzeng.com" title="nigelzeng" target="_blank">nigelzeng</a>, All rights Reserved. Theme Design by <a href="http://beiyuu.com" title="BeiYuu" target="_blank">BeiYuu</a>
